// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	chat "ChatsService/proto/chat"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChatGRPCServer is an autogenerated mock type for the ChatGRPCServer type
type ChatGRPCServer struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: ctx, req
func (_m *ChatGRPCServer) CreateMessage(ctx context.Context, req *chat.MessageCreateRequest) (*chat.MessageCreateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *chat.MessageCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.MessageCreateRequest) (*chat.MessageCreateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.MessageCreateRequest) *chat.MessageCreateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.MessageCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.MessageCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGreeterChatsServer provides a mock function with no fields
func (_m *ChatGRPCServer) mustEmbedUnimplementedGreeterChatsServer() {
	_m.Called()
}

// NewChatGRPCServer creates a new instance of ChatGRPCServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatGRPCServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatGRPCServer {
	mock := &ChatGRPCServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
