// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	chat "ChatsService/proto/chat"
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GreeterChatsClient is an autogenerated mock type for the GreeterChatsClient type
type GreeterChatsClient struct {
	mock.Mock
}

// CreateMessage provides a mock function with given fields: ctx, in, opts
func (_m *GreeterChatsClient) CreateMessage(ctx context.Context, in *chat.MessageCreateRequest, opts ...grpc.CallOption) (*chat.MessageCreateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *chat.MessageCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.MessageCreateRequest, ...grpc.CallOption) (*chat.MessageCreateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *chat.MessageCreateRequest, ...grpc.CallOption) *chat.MessageCreateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.MessageCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *chat.MessageCreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGreeterChatsClient creates a new instance of GreeterChatsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGreeterChatsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GreeterChatsClient {
	mock := &GreeterChatsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
