HTTPServer:
  Addr: "localhost"
  Port: "1000"
EnvironmentVariables:
  Environment: "development"
DataBase:
  ConnectionString: "postgres://postgres:1234@localhost/ChatsDb?sslmode=disable"
Logs:
  Path: ""
  Level: info
  MaxAge: 1
  MaxBackups: 4
Cors:
  "AllowedOrigins": [
    "http://localhost:4200"
  ]