basePath: /
definitions:
  dto.Chat:
    properties:
      id:
        type: string
      name:
        type: string
      participants:
        items:
          $ref: '#/definitions/dto.Participant'
        type: array
    required:
    - id
    - participants
    type: object
  dto.ChatCreate:
    properties:
      name:
        type: string
      participantIds:
        items:
          type: string
        type: array
    required:
    - participantIds
    type: object
  dto.ChatDetail:
    properties:
      id:
        type: string
      name:
        type: string
      participants:
        items:
          $ref: '#/definitions/dto.Participant'
        type: array
    required:
    - id
    - participants
    type: object
  dto.ChatUpdate:
    properties:
      name:
        type: string
      participantIds:
        items:
          type: string
        type: array
    required:
    - participantIds
    type: object
  dto.Error:
    properties:
      description:
        type: string
      stackTrace:
        type: string
      status:
        type: integer
    required:
    - description
    - status
    type: object
  dto.Message:
    properties:
      chatId:
        type: string
      createdAt:
        type: string
      id:
        type: string
      receiverId:
        type: string
      senderId:
        type: string
      text:
        type: string
    required:
    - chatId
    - createdAt
    - id
    - receiverId
    - senderId
    - text
    type: object
  dto.MessageUpdate:
    properties:
      text:
        type: string
    required:
    - text
    type: object
  dto.Participant:
    properties:
      id:
        type: string
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    required:
    - name
    - surname
    type: object
host: localhost:1006
info:
  contact: {}
  title: ChatsService API
  version: "1.0"
paths:
  /api/v1/chats:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Chat'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
    post:
      consumes:
      - application/json
      parameters:
      - description: Chat info
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/dto.ChatCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
  /api/v1/chats/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
    get:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ChatDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
    put:
      consumes:
      - application/json
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: string
      - description: Chat info
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/dto.ChatUpdate'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
  /api/v1/chats/user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Chat'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Chats
  /api/v1/messages:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Messages
  /api/v1/messages/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Messages
    get:
      consumes:
      - application/json
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Messages
    put:
      consumes:
      - application/json
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      - description: Message info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.MessageUpdate'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Messages
  /api/v1/messages/chat/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      security:
      - BearerAuth: []
      tags:
      - Messages
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
